### ISSUE TITLE
Respect get_queryset on views

### ISSUE THREAD

**Issue by mattjegan** [aljp/drf_model_pusher#14]
At the moment, the package requires that there is a `.queryset` class attribute on the view, a lot of the time there is not since the view or viewset uses `.get_queryset` instead. To minimise the setup cost of this package we should detect which pattern is currently being used and respect that to figure out the model. Alternatively, we could deduce it from the `.serializer_class` or `.get_serializer_class`.

**Comment by aljp** [comment]
Fixed this in 7c44914 for the ModelPusherViewMixin
