### ISSUE TITLE
Provide setting to prevent `pusher.trigger`

### ISSUE THREAD

**Issue by mattjegan** [aljp/drf_model_pusher#15]
It would be good to be able to stop pusher events from firing, for example in CI or testing. While this is possible with mocking, it would be more user friendly to provide a setting like `DRF_MODEL_PUSHER_ENABLED=False` to bypass the `pusher.trigger` call.

**Comment by aljp** [comment]
I suppose it would make sense to have a proxy class/method for our apps use of Pusher or the trigger method, pusher can be disabled and mocking would be pretty clean and mimic the Pusher API.

**Comment by mattjegan** [comment]
Yeah agreed, mocking isn't too bad as long as we document how to write tests when using this package.
